# Generated by Django 3.2 on 2021-04-16 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Find Job', 'Find Job'), ('Parties', 'Parties'), ('Computer', 'Computer'), ('Community', 'Community'), ('Birds and Animals', 'Birds and Animals'), ('Cars', 'Cars'), ('Services ', 'Services '), ('Meetings and Show', 'Meetings and Show'), ('Education', 'Education'), ('Companies Guide', 'Companies Guide')], max_length=190, null=True)),
                ('price', models.FloatField(null=True)),
                ('date_publish', models.DateTimeField(auto_now_add=True, max_length=190, null=True)),
                ('address', models.CharField(max_length=190, null=True)),
                ('content', models.TextField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=190, null=True)),
                ('name', models.CharField(max_length=190, null=True)),
                ('email', models.CharField(max_length=190, null=True)),
                ('phone', models.CharField(max_length=190, null=True)),
                ('age', models.CharField(max_length=190, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('pay', models.CharField(choices=[('free', 'free'), ('visa card', 'visa card'), ('master card', 'master card')], max_length=190, null=True)),
                ('number', models.CharField(max_length=190, null=True)),
                ('status', models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('failed', 'failed')], max_length=190, null=True)),
                ('announcement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launch.announcement')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launch.customer')),
                ('tag', models.ManyToManyField(to='launch.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='tag',
            field=models.ManyToManyField(to='launch.Tag'),
        ),
    ]
