# Generated by Django 3.2 on 2021-04-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0002_remove_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay',
            field=models.CharField(choices=[('free', 'free'), ('visa card', 'visa card'), ('master card', 'master card')], max_length=190, null=True),
        ),
    ]
