# Generated by Django 3.2 on 2021-04-16 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('launch', '0003_order_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='launch.customer'),
        ),
    ]
